pila/database.go
pila/database_test.go
pila/stack.go
pila/stack_test.go
pilad/conn.go
pilad/conn_test.go
pilad/router.go

Implement handler for GET Stacks of a Database

---

.travis.yml
dev/Dockerfile
dev/Makefile

Also fix a bug on Docker build.

Update to Go version 1.7

---

pila/stack.go
pila/stack_test.go
pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go
pilad/utils.go
pilad/utils_test.go

Part of #7 
- Introduce the `Element` type
- Implement handler for requests on a stack
- Implement handler for PUSH on a stack
- Refactoring code

Implement PUSH on a stack

---

Makefile
pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go
pilad/utils.go
pilad/utils_test.go

Implement POP on a stack

---

pila/stack.go
pila/stack_test.go
pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go
pkg/stack/stack.go
pkg/stack/stack_test.go

Part of #7 
Flushes the content of a stack.

Implement FLUSH on a stack

---

pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go

Delete stack from database

---

pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go

Part of #7
Implements handlers for PEEK operation and for fetching the status of a single stack.

Peek and status of a stack

---

pila/stack.go
pila/stack_test.go
pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go

Add SIZE operation on a stack

---

config/config.go
config/config_test.go
config/value.go
config/value_test.go
config/vars/vars.go
config/vars/vars_test.go
pilad/README.md
pilad/config.go
pilad/config_test.go
pilad/conn.go
pilad/conn_test.go
pilad/main.go
pilad/router.go

This mainly implements #9, so a piladb connection contains a Configuration that can be modified via HTTP, clip flags or environment variables.

Create configuration logic

---

config/value.go
config/value_test.go
config/vars/vars.go
pilad/config.go
pilad/main.go

Part of #9.
Adds ReadTimeout and WriteTimeout to pilad server, and makes it configurable.

Add timeouts to pilad server

---

CHANGELOG.md
pkg/version/version.go

:rocket: :rocket: :rocket: 
:rocket: :rocket: 
:rocket: 
:tada:
:raising_hand:

Release 0.1.0

---

.gitignore
.travis.yml
Makefile
README.md
dev/tests.sh

Fixes #42
* Add new script to execute tests on TravisCI gathering all coverage reports in one file.
* Update TravisCi file in order to execute this script and send data to codecov.io.
* Add codecov.io badge to README.
* Update README regarding code coverage.

Add support to codecov.io

---

CHANGELOG.md
pkg/version/version.go

Release 0.1.2

---

CHANGELOG.md
pkg/stack/stack.go
pkg/stack/stack_test.go

Small additions after #61 being merged.
cc @sprt

Add to PR #61

---

pkg/stack/stack.go

stack: use a read-write mutex

---

CHANGELOG.md

Update CHANGELOG after #63

---

CHANGELOG.md
pkg/version/version.go

See https://github.com/fern4lvarez/piladb/blob/49fd883f2646ea7cf65e11f299f730092abdf32c/CHANGELOG.md#013---2017-04-15

Release 0.1.3

---

README.md
pila/stack.go
pila/stack_test.go
pilad/README.md
pilad/conn.go
pilad/conn_test.go
pilad/router.go
pkg/stack/stack.go
pkg/stack/stack_test.go
pkg/stack/stacker.go

Implement BASE operation

---

CHANGELOG.md
pkg/version/version.go

See https://github.com/fern4lvarez/piladb/compare/v0.1.3...v0.1.4

Release 0.1.4

---

CHANGELOG.md
pkg/version/version.go

See https://github.com/fern4lvarez/piladb/compare/v0.1.4...v0.1.5

Release 0.1.5

---

.travis.yml
CHANGELOG.md

In order to be up-to-date with new releases.

Update Travis file to test against Go1.10.x
