fern4lvarez/piladb

pilad/conn.go, pilad/conn_test.go
We consider that error messages should be implicit in the HTTP Code,
so no need to print the output in plain text, which also breaks
JSON parsing tools like `jq`, which aim to be compatible with `pilad`.
Also, the Gone error  message is logged.
=> pilad: do not print output when 410 Gone

Makefile, pila/database.go, pila/database_test.go, pila/integration_test.go, pila/stack.go, pila/stack_test.go, pilad/conn.go, pilad/port.go, pilad/status.go, pilad/status_test.go, pkg/uuid/uuid.go, pkg/version/version.go
To give real uniqueness to stacks all over the pila,
we recalculate the ID of the stack once this is added
to a database.
=> pilad: set Stack id based on database and stack names

pila/database.go, pila/database_test.go, pila/pila.go, pila/pila_test.go, pila/stack.go, pila/stack_test.go, pilad/conn.go
This belongs to #7, but also expands #8.
Models (pila, database, stack) have types to define their status, i.e. `TypeStatus`.
Previously, each model had a method called `TypeStatus()`, that converted a model object directly into its status in JSON format. This wasn't the most optimal way, as some status contains others, e.g. database status needs to access all stacks statuses.
Now, there will be separate methods, one for converting the type into a `TypeStatus` type, and another method, `ToJSON`, which belongs to the `*Status` type, that will take care of the type marshaling into JSON.
=> Decouple model statuses and JSON conversion

pilad/README.md, pilad/conn.go, pilad/conn_test.go, pilad/router.go
Part of #7.
`PUT /databases/$DATABASE_ID/stacks?name=$STACK_NAME`
Creates a new `$STACK_NAME` stack belongind to database `$DATABASE_ID`.
```json
201 CREATED
{
"size": 0,
"peek": null,
"name": "stack",
"id": "714e49277eb730717e413b167b76ef78"
}
```
Returns `410 GONE` if the database does not exist.
Returns `400 BAD REQUEST` if name is not provided.
Returns `409 CONFLICT` if `$STACK_NAME` already exists.
=> pilad: create stacks on a database

pila/stack.go, pkg/stack/stack.go, pkg/stack/stacker.go
Part of #32.
This PR introduces a `Stacker` interface, which contains all methods required to implement a Stack.
This means that we can easily introduce another implementations of a Stack into the functionality of piladb. For example, now we're using a Linked List implementation. If we implement a Slice-based Stack, introducing it would just require to change one line of code in the `pila.Stack` type creation.
=> pkg/stack: add Stacker interface

config/config.go, pila/database.go, pila/stack.go, pila/stack_status_test.go, pilad/conn.go, pilad/conn_test.go, pilad/status.go, pilad/status_test.go
Part of #32 
With this commit, all dates are stored as UTC, and shown as Local. This will keep the dates consistent regardless of where  **piladb** is running.
=> Store always in UTC, show in Local

pilad/config.go, pilad/conn.go, pilad/main.go, pilad/main_test.go, pilad/utils.go, pkg/version/version.go, pkg/version/version_test.go
Part of #32 
Now, version of piladb is set in `version.VERSION.`
=> Add `-v` flag and VERSION set

pila/database.go, pila/database_test.go, pila/stack.go, pila/stack_test.go
This commit does not imply API breaking changes, so it can be added in the next
0.1.X release.
Now it is possible to create a `pila.Stack` using a custom
implementation that satisfies the `stack.Stacker` interface, e.g.
```go
type TestStack struct{}
func (s *TestStack) Push(element interface{}) { return }
func (s *TestStack) Pop() (interface{}, bool) { return nil, false }
func (s *TestStack) Size() int                { return 0 }
func (s *TestStack) Peek() interface{}        { return nil }
func (s *TestStack) Flush()                   { return }
stack := pila.NewStackWithCustomImplementation("stack", time.Now(), &TestStack{})
```
It is also possible to create a Stack with a custom base implementation from a Database instance:
```go
id := db.CreateStackWithBase("stack", time.Now(), …
```
=> pila: allow publicly to use custom Stack implementation

CHANGELOG.md, pilad/README.md, pilad/conn.go, pilad/conn_test.go, pilad/router.go
This allows to check health-check of server in a very cheap way.
Should be included in next 0.1.X release.
=> pilad: Implement `_ping` endpoint

CHANGELOG.md, pila/stack.go, pila/stack_test.go, pilad/config_test.go, pilad/conn.go, pilad/conn_test.go
Before this fix, if you tried to `PUSH` an element using some
of the following payloads:
* `{"elent":8}`
* `{"foo":8}`
* `{1:8}`
The server wouldn't complain when parsing them, and would store a
`null` on top of the Stack. Same behavior when trying to set some config
value.
With this fix, we now check that the payload contains the word `element`
as key. Otherwise, we return an error when decoding it, that will become
a `400 Bad Request` in `pilad`.
=> Fix encoding bug when pushing a malformed payload

CHANGELOG.md, pilad/README.md, pilad/conn.go, pilad/conn_test.go, pilad/utils.go
Although we change the functionality of an endpoint, i.e. `/`, this doesn't affect functionality of pilad server, so this shall will be included in the 0.1.X series.
=> pilad: Update root handler

CHANGELOG.md, README.md, dev/Dockerfile, dev/README.md
Now that [pila.sh](https://github.com/oscillatingworks/piladb-sh) is a thing, we can add it to the official Docker image.
=> dev: add pila.sh to Dockerfile

pkg/stack/stack.go, pkg/stack/stack_test.go
In particular, `Peek` could panic, but this doesn't prevent all race conditions (see commit msg).
IMO, the stack should just embed a mutex so that the client can decide whether or not to acquire a lock.
=> stack: fix data races

CHANGELOG.md, pila/stack.go, pila/stack_test.go, pilad/README.md, pilad/conn.go, pilad/conn_test.go
Hi fern4lvarez,
This pull request fixes the code reviews from https://github.com/fern4lvarez/piladb/pull/65
1. Pull request merging to dev-0.2 instead of master
2. change handler and api name to empty to conform naming convention
3. Implement Empty function in stack.go
4. Enforce 100% code test coverage.
5. Allow maintainer to edit pull request.
Description:
Added isEmpty functionality to api. Now client can access is_empty rest call to
determine if the stack associated to the pass in stack id and db id is empty or not.
Testing Methodology:
Verify the following curl call will return is_empty = false
curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
curl -XPOST localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF …
=> New Stack operations #44: isEmpty

CHANGELOG.md, pila/stack.go, pila/stack_test.go
This PR fixes potential race conditions when updating Stack dates concurrently.
**Warning**: These changes might affect performance of Stack operations, but at this point, data integrity is more important than performance.
=> pila: add mutex control for Stack dates

pilad/config.go, pilad/config_test.go, pilad/conn.go, pilad/conn_test.go
I am not really sure if putting `isMaxStackSize` in `pilad/config.go` is the best way, feel like check full should be encapsulate in the stack itself.
I am open to suggestion.
Description:
Add a new rest endpoint FULL which checks if a particular stack is full or not.
Testing Methodology:
Verify the following curl call to full will return full = true
./bin/pilad -max-stack-size 0
curl -XPUT "localhost:1205/databases?name=MY_DATABASE"
curl -XPUT "localhost:1205/databases/MY_DATABASE/stacks?name=BOOKSHELF"
curl -XPOST localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF \
-d '{"element":{"title":"1984","author":"George Orwell","ISBN":"1595404325","comments":[]}}'
curl "localhost:1205/databases/MY_DATABASE/stacks/BOOKSHELF?full"
Verify the following curl call to full will return full = …
=> New Stack operations #44: FULL

CHANGELOG.md, Makefile, pila/database.go, pila/database_test.go, pila/stack.go, pila/stack_test.go
Motivated by [this converation in Reddit](https://www.reddit.com/r/golang/comments/65jjbe/piladb_013_released/dgazajf/), this PR provides more thread safety to manipulations on Database and Stack types.
The most common case was to add a Stack to a Database, i.e. `db.AddStack(stack)`, and remove the same stack concurrently, i.e. `db.RemoveStack(stack.ID)`. The former adds the Stack to the Database, regenerating the UUID of the stack based on the Stack and Database names, whereas the latter reads the ID of the Stack to remove it. Thus, there's a conflict when editing and consuming this ID. This case, plus others reflected on the tests are fixed now.
=> pila: do Database and Stack.ID manipulation thread safe

CHANGELOG.md, pila/stack.go, pila/stack_test.go, pilad/README.md, pilad/conn.go, pilad/conn_test.go, pilad/router.go, pkg/stack/stack.go, pkg/stack/stack_test.go, pkg/stack/stacker.go
Part of #44
The ROTATE operation will move the bottommost element of a Stack to the top, becoming this the new peak. If the Stack is empty, it won't do anything.
=> Add ROTATE stack operation

CHANGELOG.md, pila/database_test.go, pila/pila_test.go, pila/stack_status_test.go, pila/stack_test.go, pilad/README.md, pilad/conn_test.go, pkg/uuid/README.md, pkg/uuid/uuid.go, pkg/uuid/uuid_test.go
This PR supersedes https://github.com/fern4lvarez/piladb/pull/76.
We needed to replace md5 with sha1 hashing for security reasons, and originally we wanted to use an external library, like https://github.com/satori/go.uuid.
After putting some thoughts on this, we came up with the conclusion that was more sensible to keep with the philosophy of keeping the third part dependencies as small as possible. Thus, we stick compliant to RFC 4122, but using a simplified Version 5 of the UUID protocol.
=> Use UUID Version 5 replacing md5 with sha1

CHANGELOG.md, config/value.go, config/value_test.go, config/vars/vars.go, config/vars/vars_test.go, pilad/config.go, pilad/conn.go, pilad/main.go, pilad/main_test.go, pilad/server.go, pilad/server_test.go
Previously, when running a pilad server and then terminating it, it stopped immediately without caring about on-going connections.
With this change, whenever pilad server receives `SIGINT` or `SIGTERM` signals, it will wait for on-going connections until they are finished. If the connections aren't finished after the _Shutdown Timeout_ is due, they all will be interrupted and the shutdown will happen.
This _Shutdown Timeout_ can be configure with the `pilad` command with the `-shutdown-timeout` parameter, which value is 15 seconds by default. As other config values, it can be set on runtime using the `/_config` endpoint.
=> Introduce graceful shutdown to pilad server
